import { base44 } from '../api/base44Client';
export const Achievement = base44.entities.Achievement;
export const UserAchievement = base44.entities.UserAchievement;
export const User = base44.entities.User;
export const Course = base44.entities.Course;
export const Lesson = base44.entities.Lesson;
export const UserProgress = base44.entities.UserProgress;
export const UserSkillProfile = base44.entities.UserSkillProfile;
export const Game = base44.entities.Game;
export const GameProgress = base44.entities.GameProgress;
